### PR TITLE
Experimental: Optional components.

### PR DESCRIPTION
**Pull request by Symbiomatrix**
For #53.
Discards some components which no longer exist in the ui.

### CODE REVIEW

**Comment by Zyin055** [comment]
That looks like a roundabout way to remove items from the `component_map` variable. Have you tried removing the list elements from `component_map` directly? I remember trying to solve this error a long time ago and can't remember if something obvious like that worked or not.

**Comment by Symbiomatrix** [comment]
It should be possible in some way, but a couple things I've borne in mind:
1) Component_map is a by reference copy, that would be deleting from the original permanently (for the run). Not sure I wanna be doing that just yet (eg with the potential multiple reference thing), so I didn't.
2) Deleting items directly from an object over which one is currently iterating has given me runtime errors in the past, so I prefer to avoid it whenever possible to be on the safe side, even if it's roundabout and possibly not necessary. A small price to pay in this case since the dictionary is merely a handful of items.

A simple comprehension like {k:v where k,v in compmap.items() where v is not None or k not in optmap} with a second pass for remaining nulls should do the trick too.

**Comment by Zyin055** [comment]
Could you try implementing the more elegant way of removing the bad IDs from `component_map`? It makes more logical sense and simplifies things.

It would also be nice to not use yet another list to store optional IDs and instead put all the IDs in the master lists of `self.txt2img_component_ids` and `self.img2img_component_ids`

**Comment by Symbiomatrix** [comment]
Elegant way, no problem.
The separation of optional IDs was intentional - I'm not sure whether we'd like to make all components optional, as it might indicate something has gone wrong in some cases. If we do need a distinguisher, then it's either a separate object like this list, or turning the ID list into a dict / class containing metadata (eg optional or not flag, alternative source) regarding each component, which would make a bit of a mess. What do you think? You do after all already have `if component_map[comp_name] is not None` in save_config's event definition.

EDIT: I've added vlad's second_pass component. His checkboxes now are a bit unusual because they'll make a part of the interface visible with a short delay (eg second pass -> secondary sampler + upscaler parms). I can save and load a preset with second pass successfully, but oddly a preset load will only toggle it on, not off. Trying to investigate this.
Oh, was just being a silly goose. My old presets don't have second pass, that's why they didn't do anything. A new preset which has it off works perfectly fine.

I've gone ahead and added the rest of the checkboxes as optional too, they're probably necessary to make the other settings work correctly.
I'm thinking that if we want to add component remapping, it should probably be done in config_preset_dropdown_change - right after you load the preset, copy values in the config_preset under the remapped keys, and current_components picks and chooses whichever components it has available. Super simple one liner.

Yep, that works, pretty cool. I've added that too with vlad's components and the controlnet thing you have, though there might be other stuff if you can think of any. Personally I think it might be handy to map txt and img equivalents to each other.
I don't currently add the synonyms to the custom components list, that would necessitate making sure optionals work perfectly first.

One more thing: regarding the hidden component issue, perhaps you could simply make the position of the list a user setting, instead of hardcoding `if component.elem_id == "txt2img_generation_info_button" or component.elem_id == "img2img_generation_info_button":` ? Obviously not all positions would work but at least it gives the user the freedom to try.
Furthermore, it might be possible to place the component anywhere - construct the skeleton as soon as you find the 'parent' component, but defer mapping the events for it till after all the components have been found (bar optionals). Granted, you won't be able to remove the skeleton should an error occur, and it would take a bit of rework in the code, but in the regular course of events it's pretty powerful.
PresetVlad1
PresetVlad2

**Comment by Zyin055** [comment]
I added some comments to help label things.

Why are "txt2img_hr_upscaler", "txt2img_hires_steps", and "txt2img_enable_hr" in `self.optional_ids`? Is it because they don't exist in Vlad's? If so please add a comment/label for that on line 742.

In order to keep txt2img and img2img segmented and to stay in line with already existing code, please split out `self.optional_ids` into `self.txt2img_optional_component_ids` and `self.img2img_optional_component_ids`. Should be able reference the correct list on line 795 with the txt2img if check.

How does adding both "controlnet_control_mod_radio" and "controlnet_control_mode_radio" to `self.optional_ids` and `self.synonym_ids` work? Will that make the `if "controlnet_control_mod_radio" in component_name` check obsolete?

**Comment by Symbiomatrix** [comment]
> I added some comments to help label things.

Awesome.

> Why are "txt2img_hr_upscaler", "txt2img_hires_steps", and "txt2img_enable_hr" in `self.optional_ids`? Is it because they don't exist in Vlad's? If so please add a comment/label for that on line 742.

Hires steps - aye, mentioned that it's been replaced in the txt2img components section and it's also in synonyms, you're welcome to reformat to standard if you have one in mind. Although it might be less copypasta if every component that's on synonym is automatically appended to optionals, since otherwise they'd definitely crash the extension when it's a version difference.
Hr upscaler - it was mentioned in #52 . On my version it actually still exists, so that might have been a mix up on brknsoul's part (second pass model was added without replacing upscale). However, I see little harm in adding a redundant component to the optionals list to be on the safe side. Removed it for now.

PresetVlad3

> In order to keep txt2img and img2img segmented and to stay in line with already existing code, please split out `self.optional_ids` into `self.txt2img_optional_component_ids` and `self.img2img_optional_component_ids`. Should be able reference the correct list on line 795 with the txt2img if check.

I feel that's somewhat of a code redundancy, since optional & synonym are used for negation rather than addition (plus have to duplicate them for extensions in both, I guess), but you're the boss.

> How does adding both "controlnet_control_mod_radio" and "controlnet_control_mode_radio" to `self.optional_ids` and `self.synonym_ids` work? Will that make the `if "controlnet_control_mod_radio" in component_name` check obsolete?

Yep, that's the plan (should everything run correctly) - rather than edit the source data, use synonyms to rename at runtime, so to speak. Obviously that check would be removed too.

By the way, feel free to remove the "SBM" markers before merging; I use these to quick jump between code sections I've edited.

**Comment by Zyin055** [comment]
Since I don't have SD.Next installed, do you know anyone else that can do a quick sanity check to see if this is working as expected for it before merging?

**Comment by Symbiomatrix** [comment]
¯\\\_(ツ)\_\/¯
Knowing people is not my strong suit. Perhaps an open invitation on [discord](https://github.com/vladmandic/automatic/discussions/1059)? I don't really use it so I haven't a feel for the sort of folk lurking yonder.

**Comment by Zyin055** [comment]
Feel free to open up another PR if you find any other issues with SD.Next.

**Pull request merged**
