### PR TITLE
Preset auto refresh.

### PR DESCRIPTION
**Pull request by Symbiomatrix**
As I was saying, this should make a simple fix for the refresh issue. Tested on my gradio 16.2, both txt + img, add / delete / update / apply.

### CODE REVIEW

**Comment by Zyin055** [comment]
This is a much nicer implementation compared to PR #39 .

I looked at [gradio#4210](https://github.com/gradio-app/gradio/issues/4210) and don't quite understand why this workaround works. It's basically just returning a list from a function and using that for the choices. I can even simplify the code to get rid of the globals
```python
#LCONFIGTXT = []
#LCONFIGIMG = []
```
and it still works.

Can you explain what trickery is happening?

**Comment by Symbiomatrix** [comment]
The globals are the workaround, basically.
I can't fully explain why, but my guess is this: gradio keeps extra references of the choices list upon init. When you update the choices attribute to a different list reference, it will replace the choices' own reference, but not update the others, eg the one used for access. When you reuse the same reference constantly, all copies will remain up to date.

**Comment by Zyin055** [comment]
I tweaked the function to not use the global variables and it still works. I can add and delete presets to the dropdown with no problems. I'll upload it and let me know if you think it isn't working properly.

(I also renamed some variables)

**Comment by Zyin055** [comment]
I'm using Automatic1111 v1.1.0 which uses Gradio 3.28.1.

I tried just assigning the config preset list to the dropdown `choices` instead of using your new function and it's still working. Maybe something in the Gradio version bump fixed the dropdown issue?

Edit: nevermind, there's desync issues when deleting a dropdown item. The fix with using the function is needed.

**Comment by Symbiomatrix** [comment]
If you're uncomfortable with globals, you could use a singleton class as a dict wrapper, but I find that more suitable for java class. Dunno enough about gradio to access the component's existing properties besides what's handed out by inputs.
If you're testing out gradio's limits, I believe it's rather an exercise in futility; they do not seem really to prioritise robustness & extensibility as far as I've observed, amongst the sea of open issues. But you've welcome to try.

**Comment by Zyin055** [comment]
I'm not adverse to using globals. I was just saying that they weren't required for the fix to work and could be removed, since they weren't doing anything.

**Comment by Symbiomatrix** [comment]
You're absolutely right. Works without global in your version, all functions. In my test environment, it seems that when you make a copy / slice / comprehension of the list whose strings are ultimately added, and then any version of those values (even with an extend), you get the error. List of a dict's keys after being comprehended from a list seems fair game too. Copy itself doesn't break (eg items2 = items[:] and then still grabbing from items worked). So I'm out of my depth for a passable guess. Not even sure what exactly breaks the original code, though that could be discerned through process of elimination.
Abid confirmed on the issue that it's part of some major bug they're planning to fix in gradio 4. I reckon that is very far away - last month I think it was 12%, now 10%.

```
import gradio as gr

#items = ["Item 1", "Item 2", "Item 3"]
items = ["Item 1"]

def makeref(l):
    vret = []
    vret.extend(l)
    return vret

def add_item():
    global items
    new_item = f'Item {len(items) + 1}'
    items.append(new_item)
    # items = items.copy() # ERROR
    # items = items[:] # ERROR
    items = [item for item in items] # ERROR
    # items2 = items[:]
    vret = []
    vret.extend(items)
    # vret = items.copy()
    # return gr.update(choices = makeref(items))
    return gr.update(choices = vret)

def print_item(item):
    print("Selected", item)

with gr.Blocks() as demo:
    with gr.Row():
        dropd = gr.Dropdown(label="Dynamic dropdown", choices = items, type="index")
    with gr.Row():
        btnadd = gr.Button(value = 'Add item')
    with gr.Row():
        btnprt = gr.Button(value = 'Print item')
    btnadd.click(fn = add_item, inputs = [], outputs = [dropd])
    btnprt.click(fn = print_item, inputs = [dropd], outputs = [])

if __name__ == "__main__":
    demo.launch()
```

**Comment by marcsyp** [comment]
Thank you for this amazing update!  The workflow experience is improved tremendously.  I often toy with gen params and then do a batch run to see if they are really worth saving, and now I can even save a preset while the batch is still running -- amazing!

Thanks all.

**Comment by Symbiomatrix** [comment]
Glad I could help a bit.

**Pull request merged**
