### PR TITLE
Reworked tracked IDs file generation

### PR DESCRIPTION
**Pull request by Clonephaze**
I moved the contents of both txt2img and img2img tracked id files to their own separate template files. This was done for two reasons, to help make it easier to add new IDs for your users and to ensure the next part works.

Most of the new code is aimed at being able to properly append old existing files with new information in the template files. Now if you update the template files, user's files will be appended with new lines on their next reload. It will not overwrite existing data, it will only append new lines to the end of old files. 

The two new function definitions are for removing any duplications that may happen when appending files, and for removing instances of more than one new line in a row. 

Moving the files was necessary to accomplish this as the script needs to be able to read each file line by line and as far as I know that can't be copied with the old way these files were generated.

### CODE REVIEW

**Comment by Zyin055** [comment]
Thoughts on keeping `Template-config-img2img-custom-tracked-components.txt` as a .py file so the user doesn't mistake it for the real config file? Could just keep the data stored as a string variable like we currently do.
Could also make it a generic template .py type of fille and put the default `txt2img_config_presets` and `img2img_config_presets` variables there too if we wanted to. If we do this, the folder structure you have should be renamed to something more generic like /templates

**Comment by Clonephaze** [comment]
I'm sure I could do that, make the two files a single .py file. That does make sense, I was gonna suggest we add a blank file called "DONT EDIT THESE" to the folder but your suggestion is much better lol. I can make the name of the folder templates too for sure. Give me a little time. Any other changes you'd like?

**Comment by Clonephaze** [comment]
@Zyin055 Alright made the requested changes. Both text files are now one .py file and the folder was renamed. The script has the changes reflected. If you want we could avoid needing to import sys if we put the template.py file in the scripts file. Pretty sure that would let you import it without needing to direct it to the right location.

**Comment by Zyin055** [comment]
How does your line update logic work if, say, we change the comments at the top? Will it be added as a new line at the bottom of everyone's config files?

**Comment by Clonephaze** [comment]
> How does your line update logic work if, say, we change the comments at the top? Will it be added as a new line at the bottom of everyone's config files?

At the moment it only appends new lines to the bottom of the existing files, it won't modify anything there. I would like that but I can't think of a way to do it without changing peoples changes to their file. For instance if we did have it change a line we changed in the template then it would also put any erased hashtags back in their spots and users would need to go uncomment them again. I felt that was more of a downside than it was worth.

**Comment by Zyin055** [comment]
Lets take a step back and think about something. What is the problem we are trying to solve with this PR? To show new suggested fields to the user for custom tracked components.

At a high level, I think an ideal solution would include showing a list of suggested component IDs that the user can view and pick from (or write in their own). Right now this is handled by commenting/uncommenting lines in the config file. But if we separated the list of suggested IDs from the list of chosen IDs, it would allow us to update the suggested IDs in code more easily.

One possible solution would be to have a text file of just suggested IDs, and then another config file where the user can add/remove IDs by copy/pasting from the suggested ID list. But having the user open multiple text files for this would be clunky and a bad experience, so it would be nice for the UI to handle this, but that's not something I'm not willing to put time into creating.

So that takes us back to this text file manipulation solution in this PR. While it could work, it'll have flaws like preventing us from editing the comments at the top and other potential issues (I haven't looked at the details of your implementation). Is this particular solution worth the potential drawbacks that may come with it? Are there any other limitations this solution comes with?

**Comment by Clonephaze** [comment]
Main thing I wanted to accomplish with this PR is give the script the ability to auto populate newly added lines to existing component files. As it stands if you add new element ID's to your script, they don't get appended into the existing files. So there's no way for you to provide any new ID's you add to existing users, without them having to manually edit their own files with the new data. 

The method I'm suggesting allows the ability to add newly added element ID's to the users existing files so all they have to do is uncomment their needed ID's. It may not be able to add new lines if you put them before the end of the existing data right now. However it can as far as I have tested add any new lines you add at the bottom to users existing files, even if they've added their own data already. It won't overwrite their data, and it'll even include any linebreaks you place in the template. 

There are no drawbacks that weren't already an issue, if you edited the comments at the top with your current approach they wouldn't fix themselves in user's current files, plus they wont get new lines if you add them in. I'm pretty sure theres only upsides to this approach, but I could easily be missing something.

**Comment by Zyin055** [comment]
I downloaded the PR and did a bit of testing:

- If we ever did want to change the informational header text at the top then it would be added as a new line at the bottom of everyone's config file. This effectively makes it impossible for us to change that text.
- Adding new IDs to already existing categories (ie `# X/Y/Z plot (script)`) adds it at the bottom, which could easily cause confusion to the user who expects everything for that section to be grouped up next to each other under that section header.
- Over time these updates will get cluttered up in a mess at the bottom in a seemingly random order to the user.

I personally don't think these issues with the current solution are worth the ability to have new IDs auto updating themselves. If I'm going to include this functionality then a more elegant solution would be needed.

**Comment by Clonephaze** [comment]
Could you put this in draft for now? I've been keeping this in mind but can't think of any way to do it more elegantly with the current approach. I'm working on some other stuff right now, like looking into if the element ID's could just be tracked by users clicking on the fields after selecting "add custom fields". JavaScript seems to be a viable method to that approach but I've got more testing to do. I think it could work, the part I'm most worried about is having the js file update the gradio interface with the new information, I'm thinking like a list that would show up of all the element ID's clicked on (with the tab and accordion styles, plus the component-xxxx id's sorted out) like the "fields to save" list that shows up. Then users could un-check any they didn't want added, and click a save button when they've added their wanted fields.

**Pull request closed without merging**
