### PR TITLE
feat: no longer needs to restart

### PR DESCRIPTION
**Pull request by SLAPaper**
Implemented the reload config feature, now there is no need to reload whole UI after change configs.

### CODE REVIEW

**Comment by Zyin055** [comment]
Was it the Gradio version bump that allowed this to work now? I vaguely remember trying to do something similar to this on the older Gradio version.

**Comment by SLAPaper** [comment]
> Was it the Gradio version bump that allowed this to work now? I vaguely remember trying to do something similar to this on the older Gradio version.

Don't quite know this, but at this version of A1111, it seems work fine

**Comment by Zyin055** [comment]
`import typing` isn't needed in Python 3.10.6, which is the required version for A1111.

**Comment by SLAPaper** [comment]
I intended to mark None-able param as typing.Optional, but anyway it works fine now

**Comment by Zyin055** [comment]
I've been doing some more testing and I sometimes get this JSON read error when creating a new preset. Can't figure out what's causing it, what do you think?

```
Traceback (most recent call last):
  File "C:\Stuff\AI\Stable Diffusion\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Stuff\AI\Stable Diffusion\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "C:\Stuff\AI\Stable Diffusion\venv\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Stuff\AI\Stable Diffusion\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Stuff\AI\Stable Diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Stuff\AI\Stable Diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Stuff\AI\Stable Diffusion\extensions\Config-Presets\scripts\config_presets.py", line 632, in <lambda>
    fn=lambda: self.reload_config_presets_dropdown(config_preset_dropdown),
  File "C:\Stuff\AI\Stable Diffusion\extensions\Config-Presets\scripts\config_presets.py", line 701, in reload_config_presets_dropdown
    self.txt2img_config_presets = load_txt2img_config_file()
  File "C:\Stuff\AI\Stable Diffusion\extensions\Config-Presets\scripts\config_presets.py", line 156, in load_txt2img_config_file
    txt2img_config_presets = json.load(file)
  File "C:\Users\Zyin\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Zyin\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Zyin\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Zyin\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by SLAPaper** [comment]
It seems that the json file it loads doesn't exist, maybe should dig in to clarify the new preset creating procedure
Could you find a minimal steps to reproduce this error?

**Comment by Zyin055** [comment]
I couldn't consistently reproduce the error. Seems to just happen sometimes.

**Comment by Zyin055** [comment]
I'm going to focus on PR #41 since it's a much more elegant solution to this problem and seems to work 100% of the time.

**Comment by Zyin055** [comment]
Closing this PR since I merged the other one into main.

**Pull request closed without merging**
