### PR TITLE
feat: allow "Script" dropdown control

### PR DESCRIPTION
**Pull request by wywywywy**
A simple change to allow controlling the "Script" dropdown.

Example configs:

```json
    "default": {
        "script_list": "None"
    },
```

```json
    "SD Upscale": {
        "script_list": "SD upscale",
        "img2img_steps": 30,
        "img2img_denoising_strength": 0.2
    },
```

### CODE REVIEW

**Comment by Zyin055** [comment]
This does not work as you expect it to.

There is JavaScript tied to the scripts dropdown that expands/collapses the script HTML section. Simply selecting the value in the dropdown does not trigger the JavaScript. The same problem exists with the Hires fix checkbox, which required extra code to trigger. You can see this in `config_presets.js: function config_preset_dropdown_change()`. The same thing would need to be applied here if you want this functionality to work.

But this also opens up the door to supporting the components within the scripts. Perhaps the suggestion you made in #34 would be a solution for that so all the components don't clog up the UI when creating a new preset. Basically make a new file that the user can edit for a custom list of component IDs, then show that in the config preset creation UI below the normal components. Would you like to try making that?

**Comment by wywywywy** [comment]
So dropdown boxes seem to work differently to checkboxes, and this change I'm proposing actually works without change the javascript. I've been testing it all day on both Firefox and Chrome.

**Comment by Zyin055** [comment]
I'm using Edge and changing the Script dropdown does not display the scripts body.

**Comment by wywywywy** [comment]
I tested in Edge and also another 2 computers, but didn't see the problem you're describing.

Anyway, I've updated the JS. But seeing as it doesn't happen on my end, can you give it a try please.

**Comment by Zyin055** [comment]
Doesn't work. Upon further inspection, I don't think this particular problem is solvable.

Each script body in the HTML does not have a unique selector that corresponds to the script dropdown values, so it's impossible to know which script body corresponds to which script dropdown value. Since we can't target the precise element we can't show it when appropriate.

The script bodies are in the same order they appear in the script dropdown, but this doesn't help either. I briefly looked into the nth-child() selector but that wouldn't work because other extensions, such as ControlNet and DynamicPrompts, inject their HTML here which would screw it up.

**Comment by Zyin055** [comment]
This works now after I updated to the latest A1111 commit (March 29). Looks like they changed how the Gradio dropdown HTML works. I'm busy with other stuff right now so I'll look into it more later.

**Comment by Zyin055** [comment]
So they bumped the Gradio version up to 3.23 https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/4697def23516ee05fbbb01f8cf6d38e9f3b19dd5 on March 25 which changes how Gradio dropdowns work. One effect of this is that the dropdown values cannot be set via JavaScript anymore, but changing them via Python triggers any relevant events to be fired.

So today I added new functionality to add any custom elements with an ID in a separate config file. I'll upload it after done playtesting.

**Pull request closed without merging**
