### PR TITLE
Update config_presets.py

### PR DESCRIPTION
**Pull request by uorufu**
Adding CMD flag to change config preset directory.

`--configpresets-dir "C:\Path\To\configpresets"`

Useful for sharing config presets when using multiple instances of automatic1111 or forge.

### CODE REVIEW

**Comment by uorufu** [comment]
I could have just changed 
`BASEDIR = scripts.basedir()` to `whatever = scripts.basedir()`
and added two lines
`from modules import shared`
`BASEDIR  = shared.cmd_opts.configpresets_dir or os.path.join(whatever)`
and be done with two lines, but I felt it might be confusing to call a potentially external directory as BASEDIR and ended up changing all BASEDIRS in entire script instead for clarity.

**Comment by Zyin055** [comment]
Interesting.

Is there a reason you chose not to use symlinks for something like this?

**Comment by uorufu** [comment]
Could've. I already used dir cmd flags for models/vae/lora's/etc from the built in cmd flags in automatic1111/forge, seemed appropriate to use the same method for extensions.

**Comment by Zyin055** [comment]
I'm getting:
```
configpresets_dir = shared.cmd_opts.configpresets_dir or os.path.join(BASEDIR) #add --configpresets-dir "C:\Path\To\configpresets" to CMD flags to change config preset directory.
AttributeError: 'Namespace' object has no attribute 'configpresets_dir'
```
I don't know how their arg parsing system works. It looks like we'd need to add a line to `modules/cmd_args.py`?

**Comment by uorufu** [comment]
That's strange, tested it with both automatic1111 and forge but worked fine for both. It shouldnt get an attribute error from calling BASEDIR as it is defined just before. 
Either way nothing should need to be added to cmd_args.py

Can't replicate it.

Could check 
`print("   >>>" + BASEDIR)`
`print("   >>>" + os.path.join(BASEDIR))`
after `BASEDIR = scripts.basedir() `

to see if maybe it goes wrong on os.path.join... Honestly I don't think it needs to be used as I always get the same result for both lines, but I seen others use it that way. 

`configpresets_dir = shared.cmd_opts.configpresets_dir or os.path.join(BASEDIR)`
should default to `os.path.join(BASEDIR)` and thus run the script as normal unless 'shared.cmd_opts.configpresets_dir' is defined (by setting cmd flag)

**Comment by Zyin055** [comment]
`os.path.join(BASEDIR)` returns the same value as `BASEDIR`.

It's the `shared.cmd_opts.configpresets_dir` part that's erroring because `configpresets_dir` is not a variable that exists in `shared.cmd_opts`.

**Comment by uorufu** [comment]
Sorry, i had this functioning for myself for quite some time and forgot one thing indeed. So sorry.
Just a sec as I fix the pull

**Comment by uorufu** [comment]
Had completely forgotting about the existance of preload.py.

Should work now, although I am traveling for 2 days so cant test it.

**Comment by Zyin055** [comment]
Still isn't working for me, `shared.cmd_opts.configpresets_dir` still comes up empty.

The shortcut I'm using to test has the Target set to: D:\AI\SD\stable-diffusion-webui-forge-1.10\webui-user.bat --configpresets-dir "C:\Users\Zyin055\Desktop"

**Comment by uorufu** [comment]
Cmd flags go into webui-user.bat at

set COMMANDLINE_ARGS=
--configpresets-dir "C:\Users\Zyin055\Desktop"
As it has to bring the flags along until it launches the webui.

**Comment by Zyin055** [comment]
Ah, that was it.

**Comment by Zyin055** [comment]
Can you think of anything to change/tweak before merging?

**Comment by uorufu** [comment]
Not specifically for this functionality.

**Pull request merged**
