### PR TITLE
Has save feature, need to relocate textfield later

### PR DESCRIPTION
**Pull request by Gerschel**
Basic save feature implemented. Wish I didn't have to revert back to this one because of some issues on my end. But this would do for now. I left this one in slight a slop phase, it was a commit for a milestone, but I don't have all my clean-up and other parts of it I was working on. Will pick up where I left off later. Maybe other's find the issue with the webui and get it resolved.

### CODE REVIEW

**Comment by Zyin055** [comment]
Could you explain what happened here? This is my first time using GitHub for anything other than me pushing my code to my own solo repos.

**Comment by wywywywy** [comment]
@Gerschel There's a bunch of good stuff in there. Maybe this should be multiple PRs, separated by functionality, to make reviewing & merging easier.

**Comment by Zyin055** [comment]
@Gerschel Were you going to make a pull request with the save functionality, or is not ready yet? Thanks for your contributions btw.

**Comment by Gerschel** [comment]
Here's the thing. I had done some work on this topic prior. I wanted to incorporate presets into my scripts, but wanted to do an over-arching one so I didn't have to include it in every project.  
Once I realized that I would lose ownership of my code through the attached license, it hindered me from being able to contribute the same code I would use in my own projects.  
I don't know what the future looks like. But if the code I write was compatible to some extent, to other projects, or became project agnostic for projects using gradio, and it became something I put a lot of time in to, I wanted the retain the ability to generate income from it, to claim ownership.  
Programming is not my job, I'm a carepenter in the carpenter's union, I've broken my back twice. I see other's making income from providing generating services, I just don't want to burn that oppurtunity if I lose functionality in my leg again.

**Comment by Gerschel** [comment]
I really do want to help though, and I know shit. I just don't know how to proceed with helping, without screwing myself over.

**Pull request closed without merging**
